Operations on Array

In [1]:
import numpy as np

In [6]:
array = np.array([0,1,2,3,4,5,6,7,8,9])

print("array : ", array)
print("slicing : ", array[2:5])
print("slicing with step : ", array[2:9:3])


array :  [0 1 2 3 4 5 6 7 8 9]
slicing :  [2 3 4]
slicing with step :  [2 5 8]


In [7]:
array_2d = np.array([[0,1,2,3,4],
                     [5,6,7,8,9],
                     [10,11,12,13,14]])

print("entire row : \n", array_2d[1])
print("entire column : \n", array_2d[:, 2])

entire row : 
 [5 6 7 8 9]
entire column : 
 [ 2  7 12]


Sorting

In [9]:
unsorted_array = np.array([5, 2, 9, 1, 5, 6])
print("Sorted array : ", np.sort(unsorted_array))
print("Sorted array in descending order : ", np.sort(unsorted_array)[::-1])

unsorted_2d_array = np.array([[5, 2, 9],
                              [1, 5, 6],
                              [3, 8, 4]])
print("Sorted 2D array along axis 0 (row wise sorting) : \n", np.sort(unsorted_2d_array, axis=0))
print("Sorted 2D array along axis 1 (column wise sorting) : \n", np.sort(unsorted_2d_array, axis=1))

Sorted array :  [1 2 5 5 6 9]
Sorted array in descending order :  [9 6 5 5 2 1]
Sorted 2D array along axis 0 (row wise sorting) : 
 [[1 2 4]
 [3 5 6]
 [5 8 9]]
Sorted 2D array along axis 1 (column wise sorting) : 
 [[2 5 9]
 [1 5 6]
 [3 4 8]]


##Filtering and Mask

In [6]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array with elements greater than 5 : ", array[array > 5])
mask = array < 5
print("Mask for elements less than 5 : ", mask)
print("Elements less than 5 using mask : ", array[mask])

indeces = np.array([0, 2, 4, 6, 8])
print("Elements at specified indices : ", array[indeces])

where_condition = np.where(array > 5)
print("Where condition for elements greater than 5 : ", where_condition)
print("Indices of elements greater than 5 : ", where_condition[0])
print("Elements greater than 5 using np.where : ", array[where_condition])

condition_arraay = np.where(array < 5, array, -1)
print("Condition array with elements less than 5 replaced by -1 : ", condition_arraay)


Array with elements greater than 5 :  [ 6  7  8  9 10]
Mask for elements less than 5 :  [ True  True  True  True False False False False False False]
Elements less than 5 using mask :  [1 2 3 4]
Elements at specified indices :  [1 3 5 7 9]
Where condition for elements greater than 5 :  (array([5, 6, 7, 8, 9]),)
Indices of elements greater than 5 :  [5 6 7 8 9]
Elements greater than 5 using np.where :  [ 6  7  8  9 10]
Condition array with elements less than 5 replaced by -1 :  [ 1  2  3  4 -1 -1 -1 -1 -1 -1]


arrat adding and concating

In [15]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_result = np.concatenate((array_1, array_2))

print("Concatenated array : ", array_result)

array_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("adding in row : \n", np.vstack((array_2d, array_1)))
print("adding in column : \n", np.hstack((array_2d, np.array([[1,3],[2,4]]))))

print("compatibility : ", np.shape(array_1) == np.shape(array_2))



Concatenated array :  [1 2 3 4 5 6]
adding in row : 
 [[1 2 3]
 [4 5 6]
 [1 2 3]]
adding in column : 
 [[1 2 3 1 3]
 [4 5 6 2 4]]
compatibility :  True
