numpy basics

In [1]:
import numpy as np

#creating different dimentional array

In [ ]:
#1D array also known as vector
array_1_d = np.array([1,2,3,4,5])
print("1 dimentional array \n", array_1_d)

#2D array is also known as matrix
array_2_d = np.array([[1,2,3],[4,5,6]])
print("2 dimentional array \n", array_2_d)

#3D array is also known as tensor
array_3_d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3 dimentional array \n", array_3_d)

1 dimentional array 
 [1 2 3 4 5]
2 dimentional array 
 [[1 2 3]
 [4 5 6]]
3 dimentional array 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


list vs array

In [4]:
list_any = [1,2,3]
print("after multiplying a scaler with list :", list_any * 2)

array_any = np.array(list_any)
print("after multiplying a scaler with array :", array_any * 2)

after multiplying a scaler with list : [1, 2, 3, 1, 2, 3]
after multiplying a scaler with array : [2 4 6]


creating different types of matrices

In [14]:
zeros = np.zeros((3,3))
print("Matrix of zeros\n", zeros)

ones = np.ones((3,3))
print("Matrix of ones\n", ones)

matrix_of_any_specific_number = np.full((3,3),9)
print("Matrix of any specifif number\n", matrix_of_any_specific_number)

matrix_of_random_number = np.random.random((3,4))
print("Matrix of random number\n",matrix_of_random_number)

sequence = np.arange(5,15,2)
print("Matrix of sequence of number starting from 5 to 14, step 2\n", sequence)

Matrix of zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrix of ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix of any specifif number
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Matrix of random number
 [[0.97767544 0.33867256 0.60036694 0.78235741]
 [0.45402862 0.02015215 0.91804697 0.38810722]
 [0.7876438  0.80747643 0.56345153 0.20913446]]
Matrix of sequence of number starting from 5 to 14, step 2
 [ 5  7  9 11 13]


Properties

In [15]:
array = np.array([[12,21,23],[34,23,12]])

print("shape : ", array.shape)
print("Dimention : ", array.ndim)
print("Size : ", array.size)
print("Data type : ", array.dtype)

shape :  (2, 3)
Dimention :  2
Size :  6
Data type :  int64


Array Reshaping

In [22]:
original_array = np.array([1,2,3,4,5,6,7,8,9])
print("Original array : ", original_array)

reshaped = original_array.reshape((3,3))
print("reshaped array : \n", reshaped)

flattend = reshaped.flatten()
print("flattend array : \n", flattend)

#ravel returns view, instead of copy
raveled = reshaped.ravel()
print("raveled array : \n", raveled)

transpose = reshaped.T
print("transposed : \n", transpose)

Original array :  [1 2 3 4 5 6 7 8 9]
reshaped array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
flattend array : 
 [1 2 3 4 5 6 7 8 9]
raveled array : 
 [1 2 3 4 5 6 7 8 9]
transposed : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
